/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
 * Generated on: 13-Jan-2022 20:28:33
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 31
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Program Files\MATLAB\R2018b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 31;
const real32_T B[31] = {
  -0.0004462581419,0.0002078039979, 0.001277646632, 0.003248555353, 0.006549410056,
     0.0114874132,  0.01819461212,  0.02659362927,  0.03638776392,  0.04707768187,
    0.05800359696,  0.06840851903,   0.0775154531,  0.08460960537,  0.08911559731,
     0.0906606093,  0.08911559731,  0.08460960537,   0.0775154531,  0.06840851903,
    0.05800359696,  0.04707768187,  0.03638776392,  0.02659362927,  0.01819461212,
     0.0114874132, 0.006549410056, 0.003248555353, 0.001277646632,0.0002078039979,
  -0.0004462581419
};
